  
# Assumes DOPPLER_TOKEN, DOPPLER_IMPORT_PROJECT, and DOPPLER_IMPORT_CONFIG are all set

name: Import Secrets

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Install CLI
      uses: dopplerhq/cli-action@v1
    - name: Test CLI
      env:
        DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        MULTI_LINE: ${{ secrets.MULTI_LINE }}
        MY_SECRET: ${{ secrets.MY_SECRET }}
        SINGLE_QUOTE: ${{ secrets.SINGLE_QUOTE }}
      run: doppler -p ${{ secrets.DOPPLER_IMPORT_PROJECT }} -c ${{ secrets.DOPPLER_IMPORT_CONFIG }} secrets upload <(env)
