name: Doppler secrets from outputs

on: [push]

jobs:
  secrets-fetch-sa-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for obtaining the OIDC JWT from Github
    steps:
      - uses: dopplerhq/secrets-fetch-action@rgharris/oidc # update to use @v1.3.0 after launch
        id: doppler
        with:
          auth-method: oidc
          doppler-identity-id: a89a5db4-b9a6-450e-9db1-d3592d5c645b
          doppler-project: backend
          doppler-config: dev
          doppler-api-domain: staging-api.doppler.com
      - run: echo "DOPPLER_PROJECT is ${{ steps.doppler.outputs.DOPPLER_PROJECT }} (Doppler meta environment variables are unmasked)"
      - run: echo "TEST is ${{ steps.doppler.outputs.TEST }} (secret masked output, sha:$(echo "${{ steps.doppler.outputs.TEST }}" | sha1sum)"

  doppler-cli-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for obtaining the OIDC JWT from Github
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get OIDC Token
        uses: actions/github-script@v6
        id: get-oidc-token
        with:
          script: |
            const gh = require('@actions/core')
            const id_token = await gh.getIDToken()
            core.setOutput('oidc_token', id_token)
      - run: ./doppler oidc login --api-host https://staging-api.doppler.com --scope=. --identity=a89a5db4-b9a6-450e-9db1-d3592d5c645b --token=${{ steps.get-oidc-token.outputs.oidc_token }}
      - run: ./doppler projects
      - run: ./doppler secrets
      - run: echo "sha(TEST) = $(./doppler secrets get TEST --plain | sha1sum)"
