  
# Assumes DOPPLER_TOKEN, DOPPLER_IMPORT_PROJECT, and DOPPLER_IMPORT_CONFIG are all set

name: Import Secrets

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Install CLI
      uses: dopplerhq/cli-action@v1
    - name: Import Secrets
      env:
        DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        ALL_SECRETS: ${{ toJson(secrets) }}
      run: doppler -p ${{ secrets.DOPPLER_IMPORT_PROJECT }} -c ${{ secrets.DOPPLER_IMPORT_CONFIG }} secrets upload <(echo "$ALL_SECRETS" | jq 'del(.DOPPLER_TOKEN,.GITHUB_TOKEN,.DOPPLER_IMPORT_CONFIG,.DOPPLER_IMPORT_PROJECT)')
